<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class RespuestasUsuarios extends Model
{
    use HasFactory;

    protected $fillable = [
        'email',
        'categoria',
        'respuesta_uno', 
        'correcta_uno',
        'respuesta_dos', 
        'correcta_dos',
        'respuesta_tres', 
        'correcta_tres',
        'respuesta_cuatro', 
        'correcta_cuatro',
        'respuesta_cinco', 
        'correcta_cinco',
        'respuesta_seis', 
        'correcta_seis',
        'respuesta_siete', 
        'correcta_siete',
        'respuesta_ocho', 
        'correcta_ocho',
        'respuesta_nueve', 
        'correcta_nueve',
        'respuesta_diez', 
        'correcta_diez',
        'respuesta_once', 
        'correcta_once',
        'respuesta_doce', 
        'correcta_doce',
        'respuesta_trece', 
        'correcta_trece',
        'respuesta_catorce', 
        'correcta_catorce',
        'respuesta_quince', 
        'correcta_quince',
        'respuesta_diezyseis', 
        'correcta_diezyseis',
        'respuesta_diezysiete', 
        'correcta_diezysiete',
        'respuesta_diezyocho', 
        'correcta_diezyocho',
        'respuesta_diezynueve', 
        'correcta_diezynueve',
        'respuesta_veinte', 
        'correcta_veinte',
        'respuesta_veinteyuno', 
        'correcta_veinteyuno',
        'respuesta_veinteydos', 
        'correcta_veinteydos',
        'respuesta_veinteytres', 
        'correcta_veinteytres',
        'respuesta_veinteycuatro', 
        'correcta_veinteycuatro',
        'respuesta_veinteycinco', 
        'correcta_veinteycinco',
        'respuesta_veinteyseis', 
        'correcta_veinteyseis',
        'respuesta_veinteysiete', 
        'correcta_veinteysiete',
        'respuesta_veinteyocho', 
        'correcta_veinteyocho',
        'respuesta_veinteynueve', 
        'correcta_veinteynueve',
        'respuesta_treinta', 
        'correcta_treinta',
        'respuesta_teintayuno', 
        'correcta_teintayuno',
        'respuesta_teintaydos', 
        'correcta_teintaydos',
        'respuesta_teintaytres', 
        'correcta_teintaytres',
        'respuesta_teintaycuatro', 
        'correcta_teintaycuatro',
        'respuesta_teintaycinco', 
        'correcta_teintaycinco',
        'respuesta_teintayseis', 
        'correcta_teintayseis',
        'respuesta_teintaysiete', 
        'correcta_teintaysiete',
        'respuesta_teintayocho', 
        'correcta_teintayocho',
        'respuesta_teintaynueve', 
        'correcta_teintaynueve',
        'respuesta_cuarenta', 
        'correcta_cuarenta',
        'nro_correctas', 
        'nro_incorrectas',
    ];
}
